import os, asyncio, time, base64
from fastapi import FastAPI
from pydantic import BaseModel
import httpx
from dotenv import load_dotenv
import pdfkit
load_dotenv()

MCP_URL = os.getenv("MCP_URL", "http://mcp:9000")
SERVICE_NAME = "demo_skills"
BASE_URL = os.getenv("BASE_URL", "http://skill-runner:8002")

app = FastAPI(title="Demo Skills")

class Profile(BaseModel):
    name: str
    age: int
    goal: str
    horizon_years: int
    risk: str
    assets: dict

@app.on_event("startup")
async def register():
    await asyncio.sleep(0.5)
    async with httpx.AsyncClient() as client:
        try:
            await client.post(f"{MCP_URL}/register_skill", json={
                "name":"risk_skill",
                "base_url": BASE_URL,
                "endpoints": {"risk_calc":"/risk_calc"}
            }, timeout=5.0)
            await client.post(f"{MCP_URL}/register_skill", json={
                "name":"alloc_skill",
                "base_url": BASE_URL,
                "endpoints": {"allocate":"/allocate"}
            }, timeout=5.0)
            await client.post(f"{MCP_URL}/register_skill", json={
                "name":"pdf_skill",
                "base_url": BASE_URL,
                "endpoints": {"pdf_export":"/pdf_export"}
            }, timeout=5.0)
            print("Registered demo skills to MCP")
        except Exception as e:
            print("Failed to register to MCP:", e)

@app.post("/risk_calc")
async def risk_calc(profile: Profile):
    # demo logic: map risk text to numeric score
    mapping = {"low": 25, "medium": 50, "high": 75}
    score = mapping.get(profile.risk.lower(), 50)
    result = {"risk_score": score, "recommended_risk": profile.risk}
    return {"node":"risk_calc","output":result}

@app.post("/allocate")
async def allocate(payload: dict):
    # payload expected: {"profile": {...}, "risk_result": {...}}
    profile = payload.get("profile", {})
    risk_result = payload.get("risk_result", {})
    risk = risk_result.get("recommended_risk", "medium").lower()
    total = sum(profile.get("assets", {}).values()) if profile.get("assets") else 0
    if total <= 0:
        total = 100000  # demo default
    if risk == "low":
        alloc = {"cash": 0.5, "bonds":0.4, "stocks":0.1}
    elif risk == "high":
        alloc = {"cash": 0.05, "bonds":0.15, "stocks":0.8}
    else:
        alloc = {"cash":0.1, "bonds":0.4, "stocks":0.5}
    # scale to amounts
    amounts = {k: round(v*total,2) for k,v in alloc.items()}
    return {"node":"allocate","output":{"allocation_percent":alloc,"allocation_amounts":amounts}}

@app.post("/pdf_export")
async def pdf_export(payload: dict):
    profile = payload.get("profile", {})
    allocation = payload.get("allocation", {})
    explanation = payload.get("explanation", "Generated by demo agent")
    # For demo we return a real PDF (base64) using wkhtmltopdf via pdfkit
    html = f"""
    <html><body>
    <h1>Wealth Plan for {profile.get('name')}</h1>
    <p>Goal: {profile.get('goal')} | Horizon: {profile.get('horizon_years')} years | Risk: {profile.get('risk')}</p>
    <h2>Allocation</h2>
    <pre>{allocation}</pre>
    <h2>Explanation</h2>
    <p>{explanation}</p>
    <hr/>
    <small>demo_pdf generated at {time.ctime()}</small>
    </body></html>
    """
    try:
        out_path = '/tmp/plan.pdf'
        # pdfkit will use wkhtmltopdf installed in the container
        pdfkit.from_string(html, out_path)
        with open(out_path, 'rb') as f:
            data = f.read()
        b64 = base64.b64encode(data).decode('utf-8')
        return {"node":"pdf_export","output":{"pdf_base64": b64}}
    except Exception as e:
        return {"node":"pdf_export","output":{"html":html, "error": str(e)}}
